; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "GoodbyeDPI"
!define PRODUCT_VERSION "0.2.3 Release Candidate 3"
!define PRODUCT_PUBLISHER "HANENCIA Creative Group"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\goodbyedpi.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "GoodbyeDPI"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "Korean"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES64\GoodbyeDPI"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite try
  File "goodbyedpi-0.2.3rc3-2\0_russia_update_blacklist_file.cmd"
  File "goodbyedpi-0.2.3rc3-2\1_russia_blacklist.cmd"
  File "goodbyedpi-0.2.3rc3-2\1_russia_blacklist_dnsredir.cmd"
  File "goodbyedpi-0.2.3rc3-2\1_russia_blacklist_YOUTUBE.cmd"
  File "goodbyedpi-0.2.3rc3-2\1_russia_blacklist_YOUTUBE_ALT.cmd"
  File "goodbyedpi-0.2.3rc3-2\2_any_country.cmd"
  File "goodbyedpi-0.2.3rc3-2\2_any_country_dnsredir.cmd"
  File "goodbyedpi-0.2.3rc3-2\russia-blacklist.txt"
  File "goodbyedpi-0.2.3rc3-2\russia-youtube.txt"
  File "goodbyedpi-0.2.3rc3-2\service_install_russia_blacklist.cmd"
  File "goodbyedpi-0.2.3rc3-2\service_install_russia_blacklist_dnsredir.cmd"
  File "goodbyedpi-0.2.3rc3-2\service_install_russia_blacklist_YOUTUBE.cmd"
  File "goodbyedpi-0.2.3rc3-2\service_install_russia_blacklist_YOUTUBE_ALT.cmd"
  File "goodbyedpi-0.2.3rc3-2\service_remove.cmd"
  SetOutPath "$INSTDIR\licenses"
  File "goodbyedpi-0.2.3rc3-2\licenses\LICENSE-getline.txt"
  File "goodbyedpi-0.2.3rc3-2\LICENSES\LICENSE-goodbyedpi.txt"
  File "goodbyedpi-0.2.3rc3-2\licenses\LICENSE-uthash.txt"
  File "goodbyedpi-0.2.3rc3-2\licenses\LICENSE-windivert.txt"
  SetOutPath "$INSTDIR"
  File "goodbyedpi-0.2.3rc3-2\russia-blacklist.txt"
  File "goodbyedpi-0.2.3rc3-2\service_install_russia_blacklist.cmd"
  File "goodbyedpi-0.2.3rc3-2\service_install_russia_blacklist_dnsredir.cmd"
  File "goodbyedpi-0.2.3rc3-2\service_remove.cmd"
  SetOutPath "$INSTDIR\x86"
  File "goodbyedpi-0.2.3rc3-2\x86\goodbyedpi.exe"
  File "goodbyedpi-0.2.3rc3-2\x86\WinDivert.dll"
  File "goodbyedpi-0.2.3rc3-2\x86\WinDivert32.sys"
  File "goodbyedpi-0.2.3rc3-2\x86\WinDivert64.sys"
  SetOutPath "$INSTDIR\x86_64"
  File "goodbyedpi-0.2.3rc3-2\x86_64\goodbyedpi.exe"
  File "goodbyedpi-0.2.3rc3-2\x86_64\WinDivert.dll"
  File "goodbyedpi-0.2.3rc3-2\x86_64\WinDivert64.sys"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\GoodbyeDPI (x86).lnk" "$INSTDIR\x86\goodbyedpi.exe"
  CreateShortCut "$DESKTOP\GoodbyeDPI (x86).lnk" "$INSTDIR\x86\goodbyedpi.exe"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\GoodbyeDPI (x64).lnk" "$INSTDIR\x86_64\goodbyedpi.exe"
  CreateShortCut "$DESKTOP\GoodbyeDPI (x64).lnk" "$INSTDIR\x86_64\goodbyedpi.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\x86\goodbyedpi.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\x86\goodbyedpi.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name)는(은) 완전히 제거되었습니다."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "$(^Name)을(를) 제거하시겠습니까?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\x86_64\WinDivert64.sys"
  Delete "$INSTDIR\x86_64\WinDivert.dll"
  Delete "$INSTDIR\x86_64\goodbyedpi.exe"
  Delete "$INSTDIR\x86\WinDivert64.sys"
  Delete "$INSTDIR\x86\WinDivert32.sys"
  Delete "$INSTDIR\x86\WinDivert.dll"
  Delete "$INSTDIR\x86\goodbyedpi.exe"
  Delete "$INSTDIR\licenses\LICENSE-windivert.txt"
  Delete "$INSTDIR\licenses\LICENSE-uthash.txt"
  Delete "$INSTDIR\licenses\LICENSE-goodbyedpi.txt"
  Delete "$INSTDIR\licenses\LICENSE-GETLINE.TXT"
  Delete "$INSTDIR\0_russia_update_blacklist_file.cmd"
  Delete "$INSTDIR\1_russia_blacklist.cmd"
  Delete "$INSTDIR\1_russia_blacklist_dnsredir.cmd"
  Delete "$INSTDIR\1_russia_blacklist_YOUTUBE.cmd"
  Delete "$INSTDIR\1_russia_blacklist_YOUTUBE_ALT.cmd"
  Delete "$INSTDIR\2_any_country.cmd"
  Delete "$INSTDIR\2_any_country_dnsredir.cmd"
  Delete "$INSTDIR\russia-blacklist.txt"
  Delete "$INSTDIR\russia-youtube.txt"
  Delete "$INSTDIR\service_install_russia_blacklist.cmd"
  Delete "$INSTDIR\service_install_russia_blacklist_dnsredir.cmd"
  Delete "$INSTDIR\service_install_russia_blacklist_YOUTUBE.cmd"
  Delete "$INSTDIR\service_install_russia_blacklist_YOUTUBE_ALT.cmd"
  Delete "$INSTDIR\service_remove.cmd"

  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$DESKTOP\GoodbyeDPI (x64).lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\GoodbyeDPI (x64).lnk"
  Delete "$DESKTOP\GoodbyeDPI (x86).lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\GoodbyeDPI (x86).lnk"

  RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir "$INSTDIR\x86_64"
  RMDir "$INSTDIR\x86"
  RMDir "$INSTDIR\licenses"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd