; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "HANENCIA Portable Utility"
!define PRODUCT_VERSION "20261004"
!define PRODUCT_PUBLISHER "HANENCIA Creative Group"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\HangulJasoFixer2.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Components page
!insertmacro MUI_PAGE_COMPONENTS
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "HANENCIA Portable Utility"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "Korean"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "HANENCIA Portable Utility 20261004 (다중 언어).exe"
InstallDir "C:\Portable"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show
RequestExecutionLevel admin

Section "자소 합치기2" SEC01
  SetOutPath "$INSTDIR\HangulJasoFixer2"
  SetOverwrite try
  File "HangulJasoFixer2\HangulJasoFixer2.exe"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS\HANENCIA Portable Utility"
  CreateShortCut "$SMPROGRAMS\HANENCIA Portable Utility\자소 합치기2.lnk" "$INSTDIR\HangulJasoFixer2\HangulJasoFixer2.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "Autoruns 14.11" SEC02
  SetOutPath "$INSTDIR\Autoruns"
  File "Autoruns\autoruns.chm"
  File "Autoruns\Autoruns.exe"
  File "Autoruns\Autoruns64.exe"
  File "Autoruns\Autoruns64a.exe"
  File "Autoruns\autorunsc.exe"
  File "Autoruns\autorunsc64.exe"
  File "Autoruns\autorunsc64a.exe"
  File "Autoruns\Eula.txt"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\HANENCIA Portable Utility\Autoruns.lnk" "$INSTDIR\Autoruns\Autoruns64.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "CCleaner 6.41" SEC03
  SetOutPath "$INSTDIR\CCleaner"
  File "CCleaner\CCleaner.exe"
  File "CCleaner\CCleaner64.exe"
  SetOutPath "$INSTDIR\CCleaner\Lang"
  File "CCleaner\Lang\lang-1025.dll"
  File "CCleaner\Lang\lang-1026.dll"
  File "CCleaner\Lang\lang-1027.dll"
  File "CCleaner\Lang\lang-1028.dll"
  File "CCleaner\Lang\lang-1029.dll"
  File "CCleaner\Lang\lang-1030.dll"
  File "CCleaner\Lang\lang-1031.dll"
  File "CCleaner\Lang\lang-1032.dll"
  File "CCleaner\Lang\lang-1034.dll"
  File "CCleaner\Lang\lang-1035.dll"
  File "CCleaner\Lang\lang-1036.dll"
  File "CCleaner\Lang\lang-1037.dll"
  File "CCleaner\Lang\lang-1038.dll"
  File "CCleaner\Lang\lang-1040.dll"
  File "CCleaner\Lang\lang-1041.dll"
  File "CCleaner\Lang\lang-1042.dll"
  File "CCleaner\Lang\lang-1043.dll"
  File "CCleaner\Lang\lang-1044.dll"
  File "CCleaner\Lang\lang-1045.dll"
  File "CCleaner\Lang\lang-1046.dll"
  File "CCleaner\Lang\lang-1048.dll"
  File "CCleaner\Lang\lang-1049.dll"
  File "CCleaner\Lang\lang-1050.dll"
  File "CCleaner\Lang\lang-1051.dll"
  File "CCleaner\Lang\lang-1052.dll"
  File "CCleaner\Lang\lang-1053.dll"
  File "CCleaner\Lang\lang-1054.dll"
  File "CCleaner\Lang\lang-1055.dll"
  File "CCleaner\Lang\lang-1056.dll"
  File "CCleaner\Lang\lang-1057.dll"
  File "CCleaner\Lang\lang-1058.dll"
  File "CCleaner\Lang\lang-1059.dll"
  File "CCleaner\Lang\lang-1060.dll"
  File "CCleaner\Lang\lang-1061.dll"
  File "CCleaner\Lang\lang-1062.dll"
  File "CCleaner\Lang\lang-1063.dll"
  File "CCleaner\Lang\lang-1065.dll"
  File "CCleaner\Lang\lang-1066.dll"
  File "CCleaner\Lang\lang-1067.dll"
  File "CCleaner\Lang\lang-1068.dll"
  File "CCleaner\Lang\lang-1071.dll"
  File "CCleaner\Lang\lang-1079.dll"
  File "CCleaner\Lang\lang-1081.dll"
  File "CCleaner\Lang\lang-1086.dll"
  File "CCleaner\Lang\lang-1087.dll"
  File "CCleaner\Lang\lang-1090.dll"
  File "CCleaner\Lang\lang-1092.dll"
  File "CCleaner\Lang\lang-1093.dll"
  File "CCleaner\Lang\lang-1102.dll"
  File "CCleaner\Lang\lang-1104.dll"
  File "CCleaner\Lang\lang-1109.dll"
  File "CCleaner\Lang\lang-1110.dll"
  File "CCleaner\Lang\lang-1155.dll"
  File "CCleaner\Lang\lang-2052.dll"
  File "CCleaner\Lang\lang-2070.dll"
  File "CCleaner\Lang\lang-2074.dll"
  File "CCleaner\Lang\lang-3098.dll"
  File "CCleaner\Lang\lang-5146.dll"
  File "CCleaner\Lang\lang-9999.dll"
  SetOutPath "$INSTDIR\CCleaner"
  File "CCleaner\License.txt"
  File "CCleaner\portable.dat"
  SetOutPath "$INSTDIR\CCleaner\x64"
  File "CCleaner\x64\CCleanerBugReport.exe"
  File "CCleaner\x64\CCleanerCrashDump.exe"
  File "CCleaner\x64\CCleanerDU.dll"
  File "CCleaner\x64\libwaapi.dll"
  File "CCleaner\x64\libwaheap.dll"
  File "CCleaner\x64\libwalocal.dll"
  File "CCleaner\x64\libwaresource.dll"
  File "CCleaner\x64\libwautils.dll"
  File "CCleaner\x64\libwavmodapi.dll"
  File "CCleaner\x64\wa_3rd_party_host_64.exe"
  SetOutPath "$INSTDIR\CCleaner\x86"
  File "CCleaner\x86\CCleanerBugReport.exe"
  File "CCleaner\x86\CCleanerCrashDump.exe"
  File "CCleaner\x86\CCleanerDU.dll"
  File "CCleaner\x86\libwaapi.dll"
  File "CCleaner\x86\libwaheap.dll"
  File "CCleaner\x86\libwalocal.dll"
  File "CCleaner\x86\libwaresource.dll"
  File "CCleaner\x86\libwautils.dll"
  File "CCleaner\x86\libwavmodapi.dll"
  File "CCleaner\x86\wa_3rd_party_host_32.exe"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\HANENCIA Portable Utility\CCleaner.lnk" "$INSTDIR\CCleaner\CCleaner64.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "DriverStore Explorer 1.0.26" SEC04
  SetOutPath "$INSTDIR\DriverStore Explorer"
  File "DriverStore Explorer\Rapr.exe"
  File "DriverStore Explorer\Rapr.exe.config"
  File "DriverStore Explorer\Rapr.pdb"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\HANENCIA Portable Utility\DriverStore Explorer.lnk" "$INSTDIR\DriverStore Explorer\Rapr.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "ExecTI 1.0" SEC05
  SetOutPath "$INSTDIR\ExecTI"
  File "ExecTI\ExecTI.exe"
  File "ExecTI\Winaero EULA.txt"
  SetOutPath "$INSTDIR\ExecTI\Windows 7"
  File "ExecTI\Windows 7\ExecTI.exe"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\HANENCIA Portable Utility\ExecTI.lnk" "$INSTDIR\ExecTI\ExecTI.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "FFmpeg 9.0.2" SEC06
  SetOutPath "$INSTDIR\ffmpeg\bin"
  File "ffmpeg\bin\ffmpeg.exe"
  File "ffmpeg\bin\ffplay.exe"
  File "ffmpeg\bin\ffprobe.exe"
  SetOutPath "$INSTDIR\ffmpeg\doc"
  File "ffmpeg\doc\bootstrap.min.css"
  File "ffmpeg\doc\community.html"
  File "ffmpeg\doc\default.css"
  File "ffmpeg\doc\developer.html"
  File "ffmpeg\doc\drawvg-reference.html"
  File "ffmpeg\doc\faq.html"
  File "ffmpeg\doc\fate.html"
  File "ffmpeg\doc\ffmpeg-all.html"
  File "ffmpeg\doc\ffmpeg-bitstream-filters.html"
  File "ffmpeg\doc\ffmpeg-codecs.html"
  File "ffmpeg\doc\ffmpeg-devices.html"
  File "ffmpeg\doc\ffmpeg-filters.html"
  File "ffmpeg\doc\ffmpeg-formats.html"
  File "ffmpeg\doc\ffmpeg-protocols.html"
  File "ffmpeg\doc\ffmpeg-resampler.html"
  File "ffmpeg\doc\ffmpeg-scaler.html"
  File "ffmpeg\doc\ffmpeg-utils.html"
  File "ffmpeg\doc\ffmpeg.html"
  File "ffmpeg\doc\ffplay-all.html"
  File "ffmpeg\doc\ffplay.html"
  File "ffmpeg\doc\ffprobe-all.html"
  File "ffmpeg\doc\ffprobe.html"
  File "ffmpeg\doc\general.html"
  File "ffmpeg\doc\git-howto.html"
  File "ffmpeg\doc\libavcodec.html"
  File "ffmpeg\doc\libavdevice.html"
  File "ffmpeg\doc\libavfilter.html"
  File "ffmpeg\doc\libavformat.html"
  File "ffmpeg\doc\libavutil.html"
  File "ffmpeg\doc\libswresample.html"
  File "ffmpeg\doc\libswscale.html"
  File "ffmpeg\doc\mailing-list-faq.html"
  File "ffmpeg\doc\nut.html"
  File "ffmpeg\doc\platform.html"
  File "ffmpeg\doc\style.min.css"
  SetOutPath "$INSTDIR\ffmpeg"
  File "ffmpeg\LICENSE"
  SetOutPath "$INSTDIR\ffmpeg\presets"
  File "ffmpeg\presets\libvpx-1080p.ffpreset"
  File "ffmpeg\presets\libvpx-1080p50_60.ffpreset"
  File "ffmpeg\presets\libvpx-360p.ffpreset"
  File "ffmpeg\presets\libvpx-720p.ffpreset"
  File "ffmpeg\presets\libvpx-720p50_60.ffpreset"
  SetOutPath "$INSTDIR\ffmpeg"
  File "ffmpeg\README.txt"
  File "ffmpeg\remove_sys_path.cmd"
  FILE "ffmpeg\set_sys_path.cmd"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "G Macro 2.0" SEC07
  SetOutPath "$INSTDIR\G Macro"
  File "G Macro\G Macro v2.0.exe"
  File "G Macro\gmc.inf"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\HANENCIA Portable Utility\G Macro.lnk" "$INSTDIR\G Macro\G Macro v2.0.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "Hitomi Downloader 4.2 Technical Preview (2026-09-30)" SEC08
  SetOutPath "$INSTDIR\Hitomi Downloader"
  File "Hitomi Downloader\hitomi_downloader_GUI.exe"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\HANENCIA Portable Utility\Hitomi Downloader.lnk" "$INSTDIR\Hitomi Downloader\hitomi_downloader_GUI.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "Image-Health" SEC09
  SetOutPath "$INSTDIR\Image-Health\BIN"
  File "Image-Health\BIN\7z.dll"
  File "Image-Health\BIN\7z.exe"
  File "Image-Health\BIN\gatherosstate.exe"
  File "Image-Health\BIN\libwim-15.dll"
  File "Image-Health\BIN\Never10.exe"
  File "Image-Health\BIN\ShowKeyPlus.exe"
  File "Image-Health\BIN\wget.exe"
  File "Image-Health\BIN\wimlib-imagex.exe"
  File "Image-Health\BIN\windowsmigration.diagcab"
  SetOutPath "$INSTDIR\Image-Health"
  File "Image-Health\ImageHealth.cmd"
  File "Image-Health\Readme.txt"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\HANENCIA Portable Utility\Image-Health.lnk" "$INSTDIR\Image-Health\ImageHealth.cmd"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "nosx" SEC10
  SetOutPath "$INSTDIR\nosx"
  File "nosx\nosx.hta"
  File "nosx\README.markdown"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\HANENCIA Portable Utility\nosx.lnk" "$INSTDIR\nosx\nosx.hta"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "RemoveGhosts" SEC11
  SetOutPath "$INSTDIR\RemoveGhosts"
  File "RemoveGhosts\RemoveGhosts.ps1"
  File "RemoveGhosts\run.cmd"
  File "RemoveGhosts\사용 방법.pdf"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "Ridirm" SEC12
  SetOutPath "$INSTDIR\Ridirm"
  File "Ridirm\Ridirm.exe"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\HANENCIA Portable Utility\Ridirm.lnk" "$INSTDIR\Ridirm\Ridirm.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "R-Studio Network 8.12" SEC13
  SetOutPath "$INSTDIR\R-Studio\App\RStudio"
  File "R-Studio\App\RStudio\avcodec-57.dll"
  File "R-Studio\App\RStudio\avfilter-6.dll"
  File "R-Studio\App\RStudio\avformat-57.dll"
  File "R-Studio\App\RStudio\avutil-55.dll"
  File "R-Studio\App\RStudio\DdiAPI.dll"
  File "R-Studio\App\RStudio\DdiAPI64.dll"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\de"
  File "R-Studio\App\RStudio\de\qt_de.qm"
  File "R-Studio\App\RStudio\de\qt_help_de.qm"
  File "R-Studio\App\RStudio\de\R-Viewer_de.qm"
  File "R-Studio\App\RStudio\de\rs-faq.url"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\en"
  File "R-Studio\App\RStudio\en\rs-faq.url"
  File "R-Studio\App\RStudio\en\RStudio_en.qhc"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\es"
  File "R-Studio\App\RStudio\es\qt_es.qm"
  File "R-Studio\App\RStudio\es\qt_help_es.qm"
  File "R-Studio\App\RStudio\es\R-Viewer_es.qm"
  File "R-Studio\App\RStudio\es\rs-faq.url"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\fr"
  File "R-Studio\App\RStudio\fr\qt_fr.qm"
  File "R-Studio\App\RStudio\fr\qt_help_fr.qm"
  File "R-Studio\App\RStudio\fr\R-Viewer_fr.qm"
  File "R-Studio\App\RStudio\fr\rs-faq.url"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio"
  File "R-Studio\App\RStudio\helpview.exe"
  File "R-Studio\App\RStudio\helpview.qrb"
  File "R-Studio\App\RStudio\iposfd.exe"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\ja"
  File "R-Studio\App\RStudio\ja\qt_help_ja.qm"
  File "R-Studio\App\RStudio\ja\qt_ja.qm"
  File "R-Studio\App\RStudio\ja\R-Viewer_ja.qm"
  File "R-Studio\App\RStudio\ja\rs-faq.url"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio"
  File "R-Studio\App\RStudio\libgfl311.dll"
  File "R-Studio\App\RStudio\libgfl340.dll"
  File "R-Studio\App\RStudio\Microsoft.VC90.CRT.manifest"
  File "R-Studio\App\RStudio\msvcm90.dll"
  File "R-Studio\App\RStudio\msvcp90.dll"
  File "R-Studio\App\RStudio\msvcr90.dll"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\plugins\sqldrivers"
  File "R-Studio\App\RStudio\plugins\sqldrivers\qsqlite4.dll"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\pt"
  File "R-Studio\App\RStudio\pt\qt_help_pt.qm"
  File "R-Studio\App\RStudio\pt\qt_pt.qm"
  File "R-Studio\App\RStudio\pt\R-Viewer_pt.qm"
  File "R-Studio\App\RStudio\pt\rs-faq.url"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio"
  File "R-Studio\App\RStudio\QtAV1.dll"
  File "R-Studio\App\RStudio\QtAVWidgets1.dll"
  File "R-Studio\App\RStudio\QtCLucene_.dll"
  File "R-Studio\App\RStudio\QtCore4.dll"
  File "R-Studio\App\RStudio\QtGui4.dll"
  File "R-Studio\App\RStudio\QtHelp_.dll"
  File "R-Studio\App\RStudio\QtNetwork4.dll"
  File "R-Studio\App\RStudio\QtSql4.dll"
  File "R-Studio\App\RStudio\QtWebKit4.dll"
  File "R-Studio\App\RStudio\QtXml4.dll"
  File "R-Studio\App\RStudio\R-Viewer.exe"
  File "R-Studio\App\RStudio\R-Viewer.qrb"
  File "R-Studio\App\RStudio\rln_viewer.txt"
  File "R-Studio\App\RStudio\rloginsrv.exe"
  File "R-Studio\App\RStudio\RStudio.exe"
  File "R-Studio\App\RStudio\RStudio32.exe"
  File "R-Studio\App\RStudio\RStudio64.exe"
  File "R-Studio\App\RStudio\rs_vdfio.vxd"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\ru"
  File "R-Studio\App\RStudio\ru\helpview_ru.qm"
  File "R-Studio\App\RStudio\ru\qt_help_ru.qm"
  File "R-Studio\App\RStudio\ru\qt_ru.qm"
  File "R-Studio\App\RStudio\ru\R-Viewer_ru.qm"
  File "R-Studio\App\RStudio\ru\rs-faq.url"
  File "R-Studio\App\RStudio\ru\RStudio_ru.qch"
  File "R-Studio\App\RStudio\ru\RStudio_ru.qhc"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio"
  File "R-Studio\App\RStudio\swresample-2.dll"
  File "R-Studio\App\RStudio\swscale-4.dll"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\Templates"
  File "R-Studio\App\RStudio\Templates\tpl_AVI.xml"
  File "R-Studio\App\RStudio\Templates\tpl_AVI_LIST.xml"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\Viewer"
  File "R-Studio\App\RStudio\Viewer\libgfl254.dll"
  File "R-Studio\App\RStudio\Viewer\libgfl267.dll"
  File "R-Studio\App\RStudio\Viewer\libgfl311.dll"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\w32"
  File "R-Studio\App\RStudio\w32\libeay32.dll"
  File "R-Studio\App\RStudio\w32\ssleay32.dll"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\w64"
  File "R-Studio\App\RStudio\w64\libeay32.dll"
  File "R-Studio\App\RStudio\w64\ssleay32.dll"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\zhcn"
  File "R-Studio\App\RStudio\zhcn\qt_help_zhcn.qm"
  File "R-Studio\App\RStudio\zhcn\qt_zhcn.qm"
  File "R-Studio\App\RStudio\zhcn\R-Viewer_zhcn.qm"
  File "R-Studio\App\RStudio\zhcn\rs-faq.url"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio\zhhk"
  File "R-Studio\App\RStudio\zhhk\qt_help_zhhk.qm"
  File "R-Studio\App\RStudio\zhhk\qt_zhhk.qm"
  File "R-Studio\App\RStudio\zhhk\R-Viewer_zhhk.qm"
  File "R-Studio\App\RStudio\zhhk\rs-faq.url"
  SetOutPath "$INSTDIR\R-Studio\App\RStudio"
  File "R-Studio\App\RStudio\_converter.dll"
  File "R-Studio\App\RStudio\_docx.dll"
  File "R-Studio\App\RStudio\_freeimage.dll"
  File "R-Studio\App\RStudio\_glib.dll"
  File "R-Studio\App\RStudio\_gsf.dll"
  File "R-Studio\App\RStudio\_myio.dll"
  File "R-Studio\App\RStudio\_ppt.dll"
  File "R-Studio\App\RStudio\_pptx.dll"
  File "R-Studio\App\RStudio\_wv2.dll"
  File "R-Studio\App\RStudio\_xls.dll"
  File "R-Studio\App\RStudio\_xlsx.dll"
  File "R-Studio\App\RStudio\_xml2.dll"
  File "R-Studio\App\RStudio\_zlib.dll"
  SetOutPath "$INSTDIR\R-Studio\Data"
  File "R-Studio\Data\RStudio.ini"
  File "R-Studio\Data\RStudioPortable.reg"
  File "R-Studio\Data\settings.ini"
  SetOutPath "$INSTDIR\R-Studio"
  File "R-Studio\R-StudioPortable.exe"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\HANENCIA Portable Utility\RStudio.lnk" "$INSTDIR\R-Studio\R-StudioPortable.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "Rufus 4.15" SEC14
  SetOutPath "$INSTDIR\Rufus"
  File "Rufus\Rufus.exe"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\HANENCIA Portable Utility\Rufus.lnk" "$INSTDIR\Rufus\Rufus.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "SpotiFLAC 7.2.2" SEC15
  SetOutPath "$INSTDIR\SpotiFLAC"
  File "SpotiFLAC\SpotiFLAC.exe"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\HANENCIA Portable Utility\SpotiFLAC.lnk" "$INSTDIR\SpotiFLAC\SpotiFLAC.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\HangulJasoFixer2\HangulJasoFixer2.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\HangulJasoFixer2\HangulJasoFixer2.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
  ExecWait 'cmd.exe /c ""$INSTDIR\ffmpeg\set_sys_path.cmd""'
SectionEnd

; Section descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC01} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC02} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC03} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC04} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC05} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC06} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC07} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC08} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC09} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC10} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC11} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC12} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC13} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC14} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC15} ""
!insertmacro MUI_FUNCTION_DESCRIPTION_END


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name)는(은) 완전히 제거되었습니다."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "$(^Name)을(를) 제거하시겠습니까?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  ; FFmpeg System PATH에서 설치 경로 제거
  IfFileExists "$INSTDIR\ffmpeg\remove_sys_path.cmd" 0 +3
    ExecWait '"$INSTDIR\ffmpeg\remove_sys_path.cmd"'
    Sleep 500
    
  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\SpotiFLAC\SpotiFLAC.exe"
  Delete "$INSTDIR\Rufus\Rufus.exe"
  Delete "$INSTDIR\R-Studio\R-StudioPortable.exe"
  Delete "$INSTDIR\R-Studio\Data\settings.ini"
  Delete "$INSTDIR\R-Studio\Data\RStudioPortable.reg"
  Delete "$INSTDIR\R-Studio\Data\RStudio.ini"
  Delete "$INSTDIR\R-Studio\App\RStudio\_zlib.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\_xml2.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\_xlsx.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\_xls.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\_wv2.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\_pptx.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\_ppt.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\_myio.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\_gsf.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\_glib.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\_freeimage.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\_docx.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\_converter.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\zhhk\rs-faq.url"
  Delete "$INSTDIR\R-Studio\App\RStudio\zhhk\R-Viewer_zhhk.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\zhhk\qt_zhhk.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\zhhk\qt_help_zhhk.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\zhcn\rs-faq.url"
  Delete "$INSTDIR\R-Studio\App\RStudio\zhcn\R-Viewer_zhcn.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\zhcn\qt_zhcn.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\zhcn\qt_help_zhcn.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\w64\ssleay32.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\w64\libeay32.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\w32\ssleay32.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\w32\libeay32.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\Viewer\libgfl311.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\Viewer\libgfl267.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\Viewer\libgfl254.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\Templates\tpl_AVI_LIST.xml"
  Delete "$INSTDIR\R-Studio\App\RStudio\Templates\tpl_AVI.xml"
  Delete "$INSTDIR\R-Studio\App\RStudio\swscale-4.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\swresample-2.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\ru\RStudio_ru.qhc"
  Delete "$INSTDIR\R-Studio\App\RStudio\ru\RStudio_ru.qch"
  Delete "$INSTDIR\R-Studio\App\RStudio\ru\rs-faq.url"
  Delete "$INSTDIR\R-Studio\App\RStudio\ru\R-Viewer_ru.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\ru\qt_ru.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\ru\qt_help_ru.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\ru\helpview_ru.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\rs_vdfio.vxd"
  Delete "$INSTDIR\R-Studio\App\RStudio\RStudio64.exe"
  Delete "$INSTDIR\R-Studio\App\RStudio\RStudio32.exe"
  Delete "$INSTDIR\R-Studio\App\RStudio\RStudio.exe"
  Delete "$INSTDIR\R-Studio\App\RStudio\rloginsrv.exe"
  Delete "$INSTDIR\R-Studio\App\RStudio\rln_viewer.txt"
  Delete "$INSTDIR\R-Studio\App\RStudio\R-Viewer.qrb"
  Delete "$INSTDIR\R-Studio\App\RStudio\R-Viewer.exe"
  Delete "$INSTDIR\R-Studio\App\RStudio\QtXml4.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\QtWebKit4.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\QtSql4.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\QtNetwork4.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\QtHelp_.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\QtGui4.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\QtCore4.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\QtCLucene_.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\QtAVWidgets1.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\QtAV1.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\pt\rs-faq.url"
  Delete "$INSTDIR\R-Studio\App\RStudio\pt\R-Viewer_pt.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\pt\qt_pt.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\pt\qt_help_pt.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\plugins\sqldrivers\qsqlite4.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\msvcr90.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\msvcp90.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\msvcm90.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\Microsoft.VC90.CRT.manifest"
  Delete "$INSTDIR\R-Studio\App\RStudio\libgfl340.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\libgfl311.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\ja\rs-faq.url"
  Delete "$INSTDIR\R-Studio\App\RStudio\ja\R-Viewer_ja.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\ja\qt_ja.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\ja\qt_help_ja.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\iposfd.exe"
  Delete "$INSTDIR\R-Studio\App\RStudio\helpview.qrb"
  Delete "$INSTDIR\R-Studio\App\RStudio\helpview.exe"
  Delete "$INSTDIR\R-Studio\App\RStudio\fr\rs-faq.url"
  Delete "$INSTDIR\R-Studio\App\RStudio\fr\R-Viewer_fr.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\fr\qt_help_fr.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\fr\qt_fr.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\es\rs-faq.url"
  Delete "$INSTDIR\R-Studio\App\RStudio\es\R-Viewer_es.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\es\qt_help_es.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\es\qt_es.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\en\RStudio_en.qhc"
  Delete "$INSTDIR\R-Studio\App\RStudio\en\rs-faq.url"
  Delete "$INSTDIR\R-Studio\App\RStudio\de\rs-faq.url"
  Delete "$INSTDIR\R-Studio\App\RStudio\de\R-Viewer_de.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\de\qt_help_de.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\de\qt_de.qm"
  Delete "$INSTDIR\R-Studio\App\RStudio\DdiAPI64.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\DdiAPI.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\avutil-55.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\avformat-57.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\avfilter-6.dll"
  Delete "$INSTDIR\R-Studio\App\RStudio\avcodec-57.dll"
  Delete "$INSTDIR\Ridirm\Ridirm.exe"
  Delete "$INSTDIR\RemoveGhosts\사용 방법.pdf"
  Delete "$INSTDIR\RemoveGhosts\run.cmd"
  Delete "$INSTDIR\RemoveGhosts\RemoveGhosts.ps1"
  Delete "$INSTDIR\nosx\README.markdown"
  Delete "$INSTDIR\nosx\nosx.hta"
  Delete "$INSTDIR\Image-Health\Readme.txt"
  Delete "$INSTDIR\Image-Health\ImageHealth.cmd"
  Delete "$INSTDIR\Image-Health\BIN\windowsmigration.diagcab"
  Delete "$INSTDIR\Image-Health\BIN\wimlib-imagex.exe"
  Delete "$INSTDIR\Image-Health\BIN\wget.exe"
  Delete "$INSTDIR\Image-Health\BIN\ShowKeyPlus.exe"
  Delete "$INSTDIR\Image-Health\BIN\Never10.exe"
  Delete "$INSTDIR\Image-Health\BIN\libwim-15.dll"
  Delete "$INSTDIR\Image-Health\BIN\gatherosstate.exe"
  Delete "$INSTDIR\Image-Health\BIN\7z.exe"
  Delete "$INSTDIR\Image-Health\BIN\7z.dll"
  Delete "$INSTDIR\Hitomi Downloader\hitomi_downloader_GUI.exe"
  Delete "$INSTDIR\G Macro\gmc.inf"
  Delete "$INSTDIR\G Macro\G Macro v2.0.exe"
  Delete "$INSTDIR\ffmpeg\README.txt"
  Delete "$INSTDIR\ffmpeg\remove_sys_path.cmd"
  Delete "$INSTDIR\ffmpeg\set_sys_path.cmd"
  Delete "$INSTDIR\ffmpeg\presets\libvpx-720p50_60.ffpreset"
  Delete "$INSTDIR\ffmpeg\presets\libvpx-720p.ffpreset"
  Delete "$INSTDIR\ffmpeg\presets\libvpx-360p.ffpreset"
  Delete "$INSTDIR\ffmpeg\presets\libvpx-1080p50_60.ffpreset"
  Delete "$INSTDIR\ffmpeg\presets\libvpx-1080p.ffpreset"
  Delete "$INSTDIR\ffmpeg\LICENSE"
  Delete "$INSTDIR\ffmpeg\doc\style.min.css"
  Delete "$INSTDIR\ffmpeg\doc\platform.html"
  Delete "$INSTDIR\ffmpeg\doc\nut.html"
  Delete "$INSTDIR\ffmpeg\doc\mailing-list-faq.html"
  Delete "$INSTDIR\ffmpeg\doc\libswscale.html"
  Delete "$INSTDIR\ffmpeg\doc\libswresample.html"
  Delete "$INSTDIR\ffmpeg\doc\libavutil.html"
  Delete "$INSTDIR\ffmpeg\doc\libavformat.html"
  Delete "$INSTDIR\ffmpeg\doc\libavfilter.html"
  Delete "$INSTDIR\ffmpeg\doc\libavdevice.html"
  Delete "$INSTDIR\ffmpeg\doc\libavcodec.html"
  Delete "$INSTDIR\ffmpeg\doc\git-howto.html"
  Delete "$INSTDIR\ffmpeg\doc\general.html"
  Delete "$INSTDIR\ffmpeg\doc\ffprobe.html"
  Delete "$INSTDIR\ffmpeg\doc\ffprobe-all.html"
  Delete "$INSTDIR\ffmpeg\doc\ffplay.html"
  Delete "$INSTDIR\ffmpeg\doc\ffplay-all.html"
  Delete "$INSTDIR\ffmpeg\doc\ffmpeg.html"
  Delete "$INSTDIR\ffmpeg\doc\ffmpeg-utils.html"
  Delete "$INSTDIR\ffmpeg\doc\ffmpeg-scaler.html"
  Delete "$INSTDIR\ffmpeg\doc\ffmpeg-resampler.html"
  Delete "$INSTDIR\ffmpeg\doc\ffmpeg-protocols.html"
  Delete "$INSTDIR\ffmpeg\doc\ffmpeg-formats.html"
  Delete "$INSTDIR\ffmpeg\doc\ffmpeg-filters.html"
  Delete "$INSTDIR\ffmpeg\doc\ffmpeg-devices.html"
  Delete "$INSTDIR\ffmpeg\doc\ffmpeg-codecs.html"
  Delete "$INSTDIR\ffmpeg\doc\ffmpeg-bitstream-filters.html"
  Delete "$INSTDIR\ffmpeg\doc\ffmpeg-all.html"
  Delete "$INSTDIR\ffmpeg\doc\fate.html"
  Delete "$INSTDIR\ffmpeg\doc\faq.html"
  Delete "$INSTDIR\ffmpeg\doc\drawvg-reference.html"
  Delete "$INSTDIR\ffmpeg\doc\developer.html"
  Delete "$INSTDIR\ffmpeg\doc\default.css"
  Delete "$INSTDIR\ffmpeg\doc\community.html"
  Delete "$INSTDIR\ffmpeg\doc\bootstrap.min.css"
  Delete "$INSTDIR\ffmpeg\bin\ffprobe.exe"
  Delete "$INSTDIR\ffmpeg\bin\ffplay.exe"
  Delete "$INSTDIR\ffmpeg\bin\ffmpeg.exe"
  Delete "$INSTDIR\ExecTI\Windows 7\ExecTI.exe"
  Delete "$INSTDIR\ExecTI\Winaero EULA.txt"
  Delete "$INSTDIR\ExecTI\ExecTI.exe"
  Delete "$INSTDIR\DriverStore Explorer\Rapr.pdb"
  Delete "$INSTDIR\DriverStore Explorer\Rapr.exe.config"
  Delete "$INSTDIR\DriverStore Explorer\Rapr.exe"
  Delete "$INSTDIR\CCleaner\x86\wa_3rd_party_host_32.exe"
  Delete "$INSTDIR\CCleaner\x86\libwavmodapi.dll"
  Delete "$INSTDIR\CCleaner\x86\libwautils.dll"
  Delete "$INSTDIR\CCleaner\x86\libwaresource.dll"
  Delete "$INSTDIR\CCleaner\x86\libwalocal.dll"
  Delete "$INSTDIR\CCleaner\x86\libwaheap.dll"
  Delete "$INSTDIR\CCleaner\x86\libwaapi.dll"
  Delete "$INSTDIR\CCleaner\x86\CCleanerDU.dll"
  Delete "$INSTDIR\CCleaner\x86\CCleanerCrashDump.exe"
  Delete "$INSTDIR\CCleaner\x86\CCleanerBugReport.exe"
  Delete "$INSTDIR\CCleaner\x64\wa_3rd_party_host_64.exe"
  Delete "$INSTDIR\CCleaner\x64\libwavmodapi.dll"
  Delete "$INSTDIR\CCleaner\x64\libwautils.dll"
  Delete "$INSTDIR\CCleaner\x64\libwaresource.dll"
  Delete "$INSTDIR\CCleaner\x64\libwalocal.dll"
  Delete "$INSTDIR\CCleaner\x64\libwaheap.dll"
  Delete "$INSTDIR\CCleaner\x64\libwaapi.dll"
  Delete "$INSTDIR\CCleaner\x64\CCleanerDU.dll"
  Delete "$INSTDIR\CCleaner\x64\CCleanerCrashDump.exe"
  Delete "$INSTDIR\CCleaner\x64\CCleanerBugReport.exe"
  Delete "$INSTDIR\CCleaner\portable.dat"
  Delete "$INSTDIR\CCleaner\License.txt"
  Delete "$INSTDIR\CCleaner\Lang\lang-9999.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-5146.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-3098.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-2074.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-2070.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-2052.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1155.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1110.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1109.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1104.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1102.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1093.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1092.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1090.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1087.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1086.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1081.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1079.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1071.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1068.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1067.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1066.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1065.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1063.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1062.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1061.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1060.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1059.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1058.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1057.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1056.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1055.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1054.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1053.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1052.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1051.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1050.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1049.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1048.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1046.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1045.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1044.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1043.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1042.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1041.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1040.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1038.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1037.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1036.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1035.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1034.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1032.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1031.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1030.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1029.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1028.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1027.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1026.dll"
  Delete "$INSTDIR\CCleaner\Lang\lang-1025.dll"
  Delete "$INSTDIR\CCleaner\CCleaner64.exe"
  Delete "$INSTDIR\CCleaner\CCleaner.exe"
  Delete "$INSTDIR\Autoruns\Eula.txt"
  Delete "$INSTDIR\Autoruns\autorunsc64a.exe"
  Delete "$INSTDIR\Autoruns\autorunsc64.exe"
  Delete "$INSTDIR\Autoruns\autorunsc.exe"
  Delete "$INSTDIR\Autoruns\Autoruns64a.exe"
  Delete "$INSTDIR\Autoruns\Autoruns64.exe"
  Delete "$INSTDIR\Autoruns\Autoruns.exe"
  Delete "$INSTDIR\Autoruns\autoruns.chm"
  Delete "$INSTDIR\HangulJasoFixer2\HangulJasoFixer2.exe"

  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$SMPROGRAMS\HANENCIA Portable Utility\SpotiFLAC.lnk"
  Delete "$SMPROGRAMS\HANENCIA Portable Utility\Rufus.lnk"
  Delete "$SMPROGRAMS\HANENCIA Portable Utility\RStudio.lnk"
  Delete "$SMPROGRAMS\HANENCIA Portable Utility\Ridirm.lnk"
  Delete "$SMPROGRAMS\HANENCIA Portable Utility\nosx.lnk"
  Delete "$SMPROGRAMS\HANENCIA Portable Utility\Hitomi Downloader.lnk"
  Delete "$SMPROGRAMS\HANENCIA Portable Utility\G Macro.lnk"
  Delete "$SMPROGRAMS\HANENCIA Portable Utility\ExecTI.lnk"
  Delete "$SMPROGRAMS\HANENCIA Portable Utility\DriverStore Explorer.lnk"
  Delete "$SMPROGRAMS\HANENCIA Portable Utility\CCleaner.lnk"
  Delete "$SMPROGRAMS\HANENCIA Portable Utility\Autoruns.lnk"
  Delete "$SMPROGRAMS\HANENCIA Portable Utility\자소 합치기2.lnk"

  RMDir "$SMPROGRAMS\HANENCIA Portable Utility"
  RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir "$INSTDIR\SpotiFLAC"
  RMDir "$INSTDIR\Rufus"
  RMDir "$INSTDIR\R-Studio\Data"
  RMDir "$INSTDIR\R-Studio\App\RStudio\zhhk"
  RMDir "$INSTDIR\R-Studio\App\RStudio\zhcn"
  RMDir "$INSTDIR\R-Studio\App\RStudio\w64"
  RMDir "$INSTDIR\R-Studio\App\RStudio\w32"
  RMDir "$INSTDIR\R-Studio\App\RStudio\Viewer"
  RMDir "$INSTDIR\R-Studio\App\RStudio\Templates"
  RMDir "$INSTDIR\R-Studio\App\RStudio\ru"
  RMDir "$INSTDIR\R-Studio\App\RStudio\pt"
  RMDir "$INSTDIR\R-Studio\App\RStudio\plugins\sqldrivers"
  RMDir "$INSTDIR\R-Studio\App\RStudio\plugins"
  RMDir "$INSTDIR\R-Studio\App\RStudio\ja"
  RMDir "$INSTDIR\R-Studio\App\RStudio\fr"
  RMDir "$INSTDIR\R-Studio\App\RStudio\es"
  RMDir "$INSTDIR\R-Studio\App\RStudio\en"
  RMDir "$INSTDIR\R-Studio\App\RStudio\de"
  RMDir "$INSTDIR\R-Studio\App\RStudio"
  RMDir "$INSTDIR\R-Studio"
  RMDir "$INSTDIR\Ridirm"
  RMDir "$INSTDIR\RemoveGhosts"
  RMDir "$INSTDIR\nosx"
  RMDir "$INSTDIR\Image-Health\BIN"
  RMDir "$INSTDIR\Image-Health"
  RMDir "$INSTDIR\Hitomi Downloader"
  RMDir "$INSTDIR\HangulJasoFixer2"
  RMDir "$INSTDIR\G Macro"
  RMDir "$INSTDIR\ffmpeg\presets"
  RMDir "$INSTDIR\ffmpeg\doc"
  RMDir "$INSTDIR\ffmpeg\bin"
  RMDir "$INSTDIR\ffmpeg"
  RMDir "$INSTDIR\ExecTI\Windows 7"
  RMDir "$INSTDIR\ExecTI"
  RMDir "$INSTDIR\DriverStore Explorer"
  RMDir "$INSTDIR\CCleaner\x86"
  RMDir "$INSTDIR\CCleaner\x64"
  RMDir "$INSTDIR\CCleaner\Lang"
  RMDir "$INSTDIR\CCleaner"
  RMDir "$INSTDIR\Autoruns"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd